version: "3"
services:
  frpc:
    image: snowdreamtech/frpc:latest
    container_name: frpc
    restart: always
    privileged: true
    volumes:
      - ./frpc.ini:/etc/frp/frpc.ini
    network_mode: host
